package common

const (
	StrCannotStartSrv             = "cannot start server: "
	StrErrReadConfig              = "Error reading config file, %s"
	StrErrUnableDecodeConfig      = "unable to decode into struct, %v"
	StrErrSpecifyPathName         = "please specify config path and name"
	StrErrInitSrv                 = "error initializing server: %v"
	StrErrRunServ                 = "error starting server: %v"
	StrErrUnableParseUuid         = "unable to parse uuid: %v"
	StrErrRegisterAgentTcpStream  = "error registering agent tcp stream: %v"
	StrErrRegisterClientTcpStream = "error registering client tcp stream: %v"
	StrErrCreateConn              = "error create conn : %v"
	StrErrSendAgentConn           = "error sending conn to agent stream : %v"
	StrErrGenUuid                 = "error generating new uuid: %v"
	StrInitGrpcSrv                = "Init server at "
	StrAgentConn                  = "Agent connected with id: %s"
	StrCreateTcpStream            = "created tcp stream to connId: %s"
	StrAgentDisconn               = "Agent disconnected with id: %s"
	StrClientConn                 = "Client connected"
	StrClientDisconn              = "Client disconnected"
	LogfmtErr                     = "%s : %s : %s" // service : method : err
	LogfmtInfo                    = "%s : %s : %s" // service : method : msg
	StrSvcAgent                   = "AgentService"
	StrSvcClient                  = "ClientService"
	StrConnMngr                   = "ConnManager"
	StrCliAgent                   = "AgentCli"
	StrCliClient                  = "ClientCli"
	StrHandleConnStream           = "HandleConnStream"
	StrHandleTcpStream            = "HandleTcpStream"
	StrErrReadTcpStream           = "error reading from tcp stream: %v"
	StrErrReadConnStream          = "error reading from conn stream: %v"
	StrErrWriteTcpStream          = "error writing to tcp stream: %v"
	StrErrReadTcpConn             = "error reading from tcp conn: %v"
	StrErrWriteTcpConn            = "error writing to tcp conn: %v"
	StrCmdStream                  = "CmdStream"
	StrTcpStream                  = "TcpStream"
	StrCtxDone                    = "Context done"
	StrConnStream                 = "ConnStream"
	StrGetAgents                  = "GetAgents"
	StrCreateConn                 = "CreateConn"
	StrErrGetMeta                 = "error getting metadata"
	StrSuccess                    = "Success"
)
