syntax = "proto3";
package go_cnc;
option go_package = ".;pb";

service ClientService {
  rpc GetAgents(Empty) returns(GetAgentsResponse); // getting list of connected agents from server
  rpc CreateConn(ClientConnRequest) returns (CreateConnResponse) {}; //
}

service AgentService {
  rpc CreateConnStream(Empty) returns (stream AgentConn); // from server to agent
}

service RelayService {
  // session_token goes in metadata key "session_token"
  rpc Tunnel(stream Chunk) returns (stream Chunk);
}

message Empty {}

message AgentConn {
  string connId = 1;
  string remoteAddr = 2;
  string relay_addr = 3;
  string session_token = 4;
}

message GetAgentsResponse {
  repeated Agent agents = 1;
}

message Agent {
  string id = 1;
  string desc = 2;
}

message ClientConnRequest {
  string agentId = 1;
  string remoteAddr = 2;
}

message CreateConnResponse {
  string connId = 1;
  string relay_addr = 2;
  string session_token = 3;
}

message Chunk {bytes data = 1;}
